package Advisor.Admin.ViewBills.AcceptBill;

import Advisor.Database.DataBaseHandler;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Ashwin
 */
public class AcceptBill extends javax.swing.JFrame {

    /**
     * Creates new form AcceptBill
     */
    public AcceptBill(int id,String img) {
        initComponents(id,img);
    }
    int id;
    String img;
    DataBaseHandler DBH;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(int id,String img) {

        Accept = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AmountField = new javax.swing.JTextField();
        this.id = id;
        this.img = img;
        DBH = DataBaseHandler.getInstance();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Accept.setText("Accept");
        Accept.addActionListener(this::AcceptActionPerformed);

        jLabel1.setText("Enter the Amount : ");

        AmountField.addActionListener(this::AmountFieldActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(AmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(107, 107, 107)
                                                .addComponent(Accept)))
                                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(38, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(AmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Accept)
                                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String amount = AmountField.getText();
        boolean isAmount = false;
        if(amount.isEmpty()){

        }else{
            char[] arr = amount.toCharArray();
            for(char i : arr){
                // Accept Code goes here
                isAmount = Character.isDigit(i);
            }
        }

        if(isAmount){
            System.out.println("Amount");
            double amt = Double.parseDouble(amount);
            ResultSet rs = DBH.execQuery("select profit_margin from tax_revenue where customers_id = "+id+";");
            try {
                if(rs.next()){
                    String q = " update tax_revenue set profit_margin = "+(amt+rs.getDouble(1))+" where customers_id = "+id+";" ;
                    String q1 = "delete from bills where cust_id = "+id+" AND image = '"+img+"'; ";
                    if(DBH.execUpdate(q)) {
                        if (DBH.execAction(q1)) {
                            super.dispose();
                        }
                    }

                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }else{
            System.out.println("Not Amount");
        }
    }

    private void AmountFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        AcceptActionPerformed(evt);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton Accept;
    private javax.swing.JTextField AmountField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration
}
